name: Build and deploy ASP.NET Core API to Azure Web App - TrendyFrameAvata

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PROJECT_PATH: khunghinh-server/Khunghinh.Api/Khunghinh.Api.csproj
  PUBLISH_DIR: ${{ github.workspace }}/published

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore "${{ env.PROJECT_PATH }}"

      - name: Build
        run: dotnet build "${{ env.PROJECT_PATH }}" --configuration Release --no-restore

      - name: Publish
        run: dotnet publish "${{ env.PROJECT_PATH }}" -c Release -o "${{ env.PUBLISH_DIR }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-published
          path: "${{ env.PUBLISH_DIR }}"

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-published
          path: ./drop

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D991BDE4859648ABB23B3D3BFCDA85B0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C44B7D03CB264514AA89DFDB9D8E8DDB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_60728868ACE04462BD5348D757B48C34 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: TrendyFrameAvata         # đúng tên App Service của bạn
          slot-name: Production
          package: ./drop
